version: '3'
services:
 npm:
  container_name: npm
  image: 'jc21/nginx-proxy-manager:latest'
  ports:
   - '80:80'
   - '81:81'
   - '443:443'
  volumes:
   - ./data:/data
   - ./letsencrypt:/etc/letsencrypt
  networks:
    - home
  restart: unless-stopped
networks:
  home:
    name: home
    external: true
  