entryPoints:
  https:
    address: :443
#log:
# level: INFO
api:
  insecure: true
providers:
  docker:
    endpoint: "unix://var/run/docker.sock"
    exposedByDefault: false
    network: home
  file:
    filename: /etc/traefik/fileConfig.yml
    watch: true
