version: "2.1"
services:
  sonarr:
   image: lscr.io/linuxserver/sonarr:develop
   container_name: sonarr
   environment:
    - PUID=1026
    - PGID=100
    - TZ=Europe/Madrid
   volumes:
    - /opt/docker/sonarr/config:/config
    - /mnt/usb/:/mnt/usb/
    - /mnt/syno/mediasyno:/mnt/syno/mediasyno
    - /mnt/syno/backup/sonarr:/config/backup
   ports:
    - 8989:8989
   networks:
    - arr
   restart: unless-stopped
networks:
  arr:
    external: true
    name: arr
