version: "2.1"
services:
  sonarr:
   image: lscr.io/linuxserver/sonarr:develop
   container_name: sonarr
   environment:
    - PUID=1026
    - PGID=100
    - TZ=Europe/Madrid
   volumes:
    - /opt/docker/sonarr/config:/config
    - /mnt/usb/:/mnt/usb/
    - /mnt/syno/mediasyno:/mnt/syno/mediasyno
    - /mnt/syno/backup/sonarr:/config/backup
   ports:
    - 8989:8989
   networks:
    - home
   labels:
    - "traefik.http.routers.sonarr.entrypoints=https"
    - "traefik.http.routers.sonarr.tls=true"
    - "traefik.http.routers.sonarr.rule=Host(`series.akiolab.es`)"
    - "traefik.http.services.sonarr-service.loadbalancer.server.port=8989"
    - "traefik.http.routers.sonarr.middlewares=authentik@file"
   restart: unless-stopped
networks:
  home:
    name: home
    external: true