site_name: Documentación del Servidor
nav:
  - Inicio: index.md
  - Introducción: introduccion.md
  - Infraestructura:
      - Hardware: infraestructura/hardware.md
      - Red: infraestructura/red.md
  - Docker:
      - Instalación: docker/instalacion.md
      - Contenedores: docker/contenedores.md
      - Redes y Volúmenes: docker/redes_volumenes.md
  - Aplicaciones:
      - Plex: aplicaciones/index.md
      - Grafana: aplicaciones/grafana.md
site_name: Documentación de AkioHome
site_url: https://akio1337.github.io/akiohome-docs/
use_directory_urls: false
theme:
  name: material
  language: es