site_name: AkioHome Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    #- toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  custom_dir: docs/_config/overrides
  language: es
  palette:
    - scheme: slate
      primary: deep orange
      accent: orange
repo_url: https://github.com/akio1337/akiohome
repo_name: akio1337/akiohome
extra:
  social:
    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/akio1337
    - icon: fontawesome/brands/github
      link: https://github.com/akio1337

plugins:
  - search
  - awesome-pages #Github: https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
copyright: |
  Akio &copy; 2024 <a href="https://github.com/akio1337"  target="_blank" rel="noopener">AkioHome</a>