---
version: "2.1"
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Madrid
    volumes:
      - /home/akio1337/tautulli/config:/config
      - plex-config:/plex-config
      - /mnt/hdd/backup/tautulli:/config/backups ## La carpeta en el contenedor es backups ya que Tautulli no permite modificarlo
    ports:
      - 8181:8181
    labels:
      - flame.type=application
      - flame.name=Tautulli
      - flame.url=http://akiohome:8181
      - flame.icon=chart-box
    restart: unless-stopped
volumes:
  plex-config:
    name: plex_plex-config
    external: true
