---
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Madrid
    volumes:
      - /opt/docker/tautulli/config:/config
      - /mnt/syno/backup/tautulli:/config/backups ## La carpeta en el contenedor es backups ya que Tautulli no permite modificarlo
      - plex_plex-config:/config/plex_logs
    networks:
      - home
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.entrypoints=https"
      - "traefik.http.routers.tautulli.tls=true"
      - "traefik.http.routers.tautulli.rule=Host(`stats.akiolab.es`)"
      - "traefik.http.services.tautulli-service.loadbalancer.server.port=8181"
    restart: unless-stopped
volumes: 
  plex_plex-config:
    name: plex_plex-config
    external: true
networks:
  home:
    name: home
    external: true
