---
version: "2.1"
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Madrid
    volumes:
      - /opt/docker/tautulli/config:/config
      - plex-config:/plex-config
      - /mnt/syno/backup/tautulli:/config/backups ## La carpeta en el contenedor es backups ya que Tautulli no permite modificarlo
    ports:
      - 8181:8181
    restart: unless-stopped
volumes:
  plex-config:
    name: plex_plex-config
    external: true
