version: '3.6'

services:
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - /home/akio1337/flame/app/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    ports:
      - 5005:5005
    secrets:
      - password # optional but required for (1)
    environment:
      - PASSWORD_FILE=/home/akio1337/flame/app/data/secrets
    restart: unless-stopped
    networks:
      - arr
# optional but required for Docker secrets (1)
secrets:
  password:
    file: /home/akio1337/flame/app/data/secrets

networks:
  arr:
    name: arr
    external: true
      