version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Madrid
    volumes:
      - /opt/docker/radarr/config:/config
      - /mnt/syno/descargas:/mnt/syno/descargas
      - /mnt/syno/mediasyno:/mnt/syno/mediasyno
      - /mnt/syno/backup/radarr:/config/backup
    ports:
      - 7878:7878
    networks:
      - arr
    labels:
      - flame.type=application
      - flame.name=Radarr
      - flame.url=http://akiohome:7878
      - flame.icon=filmstrip-box
    restart: unless-stopped
networks:
  arr:
    external: true
    name: arr
