version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Madrid
    volumes:
      - /opt/docker/radarr/config:/config
      - /mnt/syno/:/mnt/syno/
      - /mnt/syno/backup/radarr:/config/backup
    ports:
      - 7878:7878
    networks:
      - arr
    restart: unless-stopped
networks:
  arr:
    external: true
    name: arr
