version: '3.3'
services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - /home/akio1337/firefly/upload:/var/www/html/storage/upload
    networks:
      - firefly_iii
      - db
    env_file: stack.env
    ports:
      - 5050:8080
    labels:
      - flame.type=application
      - flame.name=Firefly
      - flame.url=http://akiohome:5050
      - flame.icon=piggy-bank
  cron:
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    command: sh -c "echo \"0 3 * * * wget -qO- http://192.168.0.24:5050/api/v1/cron/1d1b626358a6ff53e308010ce884e35c\" | crontab - && crond -f -L /dev/stdout"

  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    container_name: firefly_iii_importer
    restart: always
    depends_on:
      - app
    ports:
      - 5051:8080
    env_file: stack.env
    networks:
      - firefly_iii
    labels:
      - flame.type=application
      - flame.name=Firefly-Importer
      - flame.url=http://akiohome:5051
      - flame.icon=database-import
networks:
   db:
    name: db
    external: true
   firefly_iii: