# Thanks for trying out Viseron!
# This is a small walkthrough of the configuration to get you started.
# There are far more components and options available than what is listed here.
# See the documentation for the full list of configuration options.

## Start by adding some cameras
ffmpeg:
  camera:
    camera_1:  # This value has to be unique across all cameras
      name: Comedor
      host: #IP de la camara
      port: 554
      path: /stream1
      username: #Usuario de la camara
      password: #Contraseña de la camara
      fps: 30
      protocol: rtsp
      width: 1920
      height: 1080

mog2:
  motion_detector:
    cameras:
      camera_1:
        trigger_recorder: true
        recorder_keepalive: true
        fps: 30

## To tie everything together we need to configure one more component.
nvr:
  camera_1:  # Run NVR for camera_1

# Now you can restart Viseron and you should be good to go!
