version: "2.1"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - ROCKET_PROFILE=release
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=3012
      - DOMAIN=http://akiohome:3012
    volumes:
      - vw-data:/data
    ports:
      - 3012:3012
    restart: unless-stopped
  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./certs:/certs
      - ./caddy-data:/data
    environment:
      - DOMAIN=https://akiohome.tail21cc7.ts.net
volumes:
 vw-data: