version: "2.1"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - vw-data:/data
    networks:
      - home
    ports:
      - 3012:80
    restart: unless-stopped
volumes:
 vw-data:

networks:
 home:
  name: home
  external: true
