version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    env_file: .env
    volumes:
      - ./config:/config
    networks:
      - home
      - db
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - mariadb
networks:
   home:
    name: home
    external: true
   db:
    name: db
    external: true