version: "3.8"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
      - /mnt/usb/:/mnt/usb/
      - /mnt/hdd/backup/lidarr:/config/backup
    ports:
      - 8686:8686
    networks:
      - arr
    labels:
      - flame.type=application
      - flame.name=Lidarr
      - flame.url=https://music.akiohome.com
      - flame.icon=music-box
      - "traefik.http.routers.lidarr.entrypoints=websecure"
      - "traefik.http.routers.lidarr.tls=true"
      - "traefik.http.routers.lidarr.rule=Host(`music.akiohome.com`)"
      - "traefik.http.services.lidarr-service.loadbalancer.server.port=8686"
      - 'traefik.http.routers.lidarr.middlewares=authelia@docker'
    restart: unless-stopped
networks:
  arr:
    name: arr
    external: true 