version: "3.8"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Madrid
    volumes:
      - /opt/docker/lidarr/config:/config
      - /mnt/usb/:/mnt/usb/
      - /mnt/syno/backup/lidarr:/config/backup
    ports:
      - 8686:8686
    networks:
      - arr
    restart: unless-stopped
networks:
  arr:
    name: arr
    external: true 
