version: "3.8"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Madrid
    volumes:
      - /home/akio1337/lidarr/config:/config
      - /mnt/usb/:/mnt/usb/
      - /mnt/hdd/backup/lidarr:/config/backup
    ports:
      - 8686:8686
    networks:
      - arr
    labels:
      - flame.type=application
      - flame.name=Lidarr
      - flame.url=https://music.akiohome.com
      - flame.icon=music-box
    restart: unless-stopped
networks:
  arr:
    name: arr
    external: true 