services:
  dockerproxy: #For blocking access to another Docker API capabilities
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
        - CONTAINERS=1
        - POST=0
    ports:
        - 127.0.0.1:2375:2375
    networks:
        - home
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    user: "1026:100"
    volumes:
      - /opt/docker/homepage/config:/app/config
      - /mnt/syno:/mnt/syno
      - /mnt/hdd:/mnt/hdd
      - /mnt/usb:/mnt/usb
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    networks:
      - home
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=https"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.rule=Host(`dashboard.akiolab.es`)"
      - "traefik.http.services.homepage-service.loadbalancer.server.port=3000"
      - "traefik.http.routers.homepage.middlewares=authentik@file"
    restart: unless-stopped

networks:
  home:
    name: home
    external: true
