version: '3.7'

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.file.filename=/etc/traefik/fileConfig.yml"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "443:443"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/docker/traefik/configuration/traefik.yml:/etc/traefik/traefik.yml"
      - "/opt/docker/traefik/configuration/fileConfig.yml:/etc/traefik/fileConfig.yml"
    networks:
      - home
networks:
  home:
    external: true
