version: '3'
services:
  traefik:
    image: traefik:v3.0 # Utiliza la versión más reciente de Traefik
    container_name: traefik
    command:
      - "--configFile=/etc/traefik/traefik.yml"
      - "--providers.file.directory=/configuration/"
      - "--providers.file.watch=true"
    ports:
      - "443:443" # Puerto HTTPS
      - "8081:8080" # Puerto del panel de control de Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Monta el socket de Docker para habilitar el proveedor Docker
      - /home/akio1337/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /home/akio1337/traefik/configuration:/configuration/
      - /home/akio1337/traefik/certs:/certs/
    networks:
      - home
    restart: unless-stopped
networks:
  home:
    name: home
    external: true