services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    ports:
      - "443:443"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/docker/traefik/configuration/traefik.yml:/etc/traefik/traefik.yml"
      - "/opt/docker/traefik/configuration/fileConfig.yml:/etc/traefik/fileConfig.yml"
    networks:
      - home
    restart: always
networks:
  home:
    external: true
