entryPoints:
  websecure:
    address: :443
  web:
    address: :80
api:
  insecure: true
providers:
  docker:
    endpoint: "unix://var/run/docker.sock"
  file:
    filename: /configuration/certs-traefik.yml