version: "3"
services:
  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:latest
    environment:
      PUID: 1026
      PGID: 100
      FLATNOTES_AUTH_TYPE: "none"
    labels:
     - flame.type=application
     - flame.name=Flatnotes
     - flame.url=http://akiohome:5555
     - flame.icon=note
    volumes:
      - "/mnt/hdd/notas/:/data"
      # Optional. Allows you to save the search index in a different location:
      # - "./index:/data/.flatnotes"
      - ./config:/config
    ports:
      - "5555:8080"
    restart: unless-stopped
