version: "2.1"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Madrid
      - DOCKER_MODS=linuxserver/mods:universal-stdout-logs
      - LOGS_TO_STDOUT=/config/qBittorrent/logs/qbittorrent.log
    volumes:
      - qbittorrent-data:/config
      - /mnt/usb/descargas:/mnt/usb/descargas
      - /mnt/syno/descargas:/mnt/syno/descargas
      - /mnt/syno/Switch:/mnt/syno/Switch
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    networks:
      - arr
    labels:
      - flame.type=application
      - flame.name=qBittorrent
      - flame.url=http://akiohome:8080
      - flame.icon=download-box
    restart: unless-stopped
volumes:
 qbittorrent-data:

networks:
  arr:
    external: true
    name: arr
