version: '3'
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb
    hostname: mariadb
    container_name: mariadb
    volumes:
      - ./config-db:/config
    networks:
      - db
    restart: unless-stopped
networks:
 db:
  name: db
  external: true

