version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    network_mode: host
    restart: unless-stopped
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    network_mode: host
    volumes:
      - pgdata:/var/lib/postgresql/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    network_mode: host
    depends_on:
      - db
      - broker
    ports:
      - "8300:8000"
    volumes:
      - /home/akio133/paperless/data:/usr/src/paperless/data
      - /home/akio133/paperless/media:/usr/src/paperless/media
      - /home/akio133/paperless/export:/usr/src/paperless/export
    labels:
      - flame.type=application
      - flame.name=Paperless
      - flame.url=http://akiohome:8000
      - flame.icon=printer-off

volumes:
  data:
  pgdata:
  redisdata:
