services:
  viseron:
    image: roflcoopter/viseron:latest
    container_name: viseron
    volumes:
      - /mnt/syno/viseron/recordings:/recordings
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8888:8888
    devices:
      - /dev/dri/renderD128
    privileged: true
    restart: unless-stopped
