version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Madrid
    volumes:
      - /opt/docker/prowlarr/config:/config
      - /mnt/syno/backup/prowlarr:/config/backup
    networks:
      - home
    ports:
      - 9696:9696
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.entrypoints=https"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.rule=Host(`indexer.akiolab.es`)"
      - "traefik.http.routers.prowlarr.middlewares=authentik@file"
      - "traefik.http.services.prowlarr-service.loadbalancer.server.port=9696"
    restart: unless-stopped
networks:
  home:
    name: home
    external: true