version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Madrid
    volumes:
      - /opt/docker/prowlarr/config:/config
      - /mnt/syno/backup/prowlarr:/config/backup
    ports:
      - 9696:9696
    networks:
      - arr
    restart: unless-stopped
networks:
  arr:
    name: arr
    external: true
