version: "2.1"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - vw-data:/data
    ports:
      - 3012:3012
    restart: unless-stopped
volumes:
 vw-data: